### ISSUE TITLE
Run dangerzone from the command line

### ISSUE THREAD

**Issue by MPeti1** [firstlookmedia/dangerzone#100]
I have 2 machines, a Windows and a Linux one.  
I can't run dangerzone on the Windows machine, because it requires docker hub, which requires Hyper-V, which, if enabled, screws up VMWare VM-s.
And it seems I also can't run it on the Linux one. It's a Raspberry Pi 4, which I manage through SSH. I can't connect a screen to it, and it seems dangerzone can't run if there's no screen.

I'm out of ideas, because I don't want to reboot and lose all of the opened windows every time I need dangerzone, and then again after I finish, and I also don't want to run a VNC server on the Pi for this.
Would it be possible to make a CLI for it?

EDIT: tried to install this on my laptop, where I don't care about VMWare. HW virtualization is not supported, so it doesn't work there too

**Comment by anarcat** [comment]
this looks similar to #77

**Comment by MPeti1** [comment]
oh yeah, that feature would be cool.  
I also think it would be the easiest to implement it for a CLI

**Comment by anarcat** [comment]
@micahflee i think this issue should be closed and marked as a duplicate of #77

**Comment by MPeti1** [comment]
I'm not sure that this is a duplicate. The goal of the 2 issues are entirely different, and I also don't see creating a CLI in the discussion of #77

**Comment by anarcat** [comment]
oh maybe i meant #53, sorry.

**Comment by MPeti1** [comment]
No worries, I agree then :) And as I see that issue is already closed with a solution, so I'll close this now
