### ISSUE TITLE
Dangerzone not running on macOS 11.1 Big Sur (not responding)

### ISSUE THREAD

**Issue by altosaar** [firstlookmedia/dangerzone#102]
![image](https://user-images.githubusercontent.com/5317244/104201054-526f8580-53f7-11eb-8376-b87caab7e4fd.png)

Installed with `brew install --cask dangerzone`.

Thanks!

**Comment by JRRMDSG** [comment]
also came to post this

**Comment by danarel** [comment]
Can confirm this is an issue

**Comment by micahflee** [comment]
Fixed in version 0.1.5
