### ISSUE TITLE
Create a release for 0.1.5

### ISSUE THREAD

**Issue by simonft** [firstlookmedia/dangerzone#104]
There's a tag for 0.1.5, and the README download links point to where a 0.1.5 release artifact would be, but there's no 0.1.5 release.

**Comment by micahflee** [comment]
Sorry about that! I just made the release today.

I wanted to fix a very obnoxious macOS bug first, which after hours and hours of troubleshooting turned out to be fixed with this: https://github.com/firstlookmedia/dangerzone/commit/4c7bde09c77a1ba2a40d311fe988daf5d94ee3c8
