### ISSUE TITLE
Has Ubuntu 18.04 LTS support been dropped?

### ISSUE THREAD

**Issue by grrrrr** [firstlookmedia/dangerzone#105]
When you install Dangerzone from the repo as outlined in the [linux install steps](https://github.com/firstlookmedia/dangerzone/wiki/Installing-Dangerzone)  it only installs version `0.1.3` which seems to fail/hang on any document conversions.

I've looked through the notes on the releases page and only see mention of Ubuntu 19.10 being dropped, I assume as it is end of life.  

If it has not been dropped, could we get updated binaries for it,  as Ubuntu 18.04 is still supported until 2023-04, it would be sad to lose ability of this tool?

**Comment by MPeti1** [comment]
If I could check the version I could say for sure which version do I have, but I also was only able to install a 6 or so months old version, and it fails with failure in hostname resolution.
It's a shame that from my 5 different attempts of using this tool I was never able to convert a single PDF :/

**Comment by grrrrr** [comment]
closing as 18.04 is not listed as a supported version for v0.3
