### ISSUE TITLE
compatibility with ARM based M1 macOS

### ISSUE THREAD

**Issue by dandren** [firstlookmedia/dangerzone#109]
Will dangerzone work on the ARM M1 based Mac's running macOS Big Sur?

**Comment by micahflee** [comment]
I have not tested it because I don't have an ARM M1 Mac to test on, but it should work. Can you confirm?

**Comment by katemyers** [comment]
I've used it, and everything seems to work fine until we get the final failure. That said, not sure that is an M1 issue.
<img width="591" alt="Screen Shot 2021-06-25 at 12 57 36 PM" src="https://user-images.githubusercontent.com/1053752/123459931-ebb0e380-d5b4-11eb-9046-049715cad397.png">

**Comment by hugooalmeidaa** [comment]
in mine didn't work too, I'm using a mac with M1, and I get a message that will finish soon, but after a several minutes the software end unexpected

**Comment by lucas-salas** [comment]
Running M1 mba with Monterey Beta 6 and docker installed. Every time I try and run DangerZone it just gets stuck on this window. Not sure if it's an M1 thing or beta thing, but I figured I'd leave it here.

<img width="408" alt="DangerZoneIssue" src="https://user-images.githubusercontent.com/10609483/134444734-fcc4dbc4-031a-4604-b5f4-86ae6dbed89a.png">

**Comment by micahflee** [comment]
The latest version has been tested and works great on M1 chips.
