### ISSUE TITLE
G Data says NO!

### ISSUE THREAD

**Issue by Sp8c3** [firstlookmedia/dangerzone#112]
![AVKTray_5egMsU4PSF](https://user-images.githubusercontent.com/26257206/120939598-1546bf80-c719-11eb-93e7-d21d2b8c5373.png)

Does anyone have an Idea why G Data suddenly flags Dangerzone (V 0.1.5)?
Because it worked flawlessly all the time :(

**Comment by micahflee** [comment]
Hmm, `dangerzone-container.exe` is a Windows [symbolic link](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) for `dangerzone.exe` -- basically, these two files are the same file, but they're only stored in `dangerzone.exe` to save disk space.

I don't think sym links are used very frequently in Windows (they're used all the time in Linux), so maybe this is the problem. Can you scan just `dangerzone.exe` and see if it thinks that one is bad too?

**Comment by Sp8c3** [comment]
same problem again :(
I meanwhile made a request for false positives, so now I'm waiting for their response.
