### ISSUE TITLE
dangerzone gets stuck on cyrillic filenames

### ISSUE THREAD

**Issue by DrWhax** [firstlookmedia/dangerzone#129]
Hi!

When attempting to run dangerzone on files that have cyrillic filenames, it gets stuck. I just tested this on two documents in cyrillic and it fails, by converting them to "testing1.odt" and "testing2.odt" I don't run into the same issue.

Hope this is useful.

**Comment by micahflee** [comment]
Fixed

**Comment by DrWhax** [comment]
FWIW, this hasn't been fixed for me. I can select the document in cyrillic but after, nothing happens, it's just doing nothing I guess?

As tested on dangerzone 0.3.1 on macos catalina.
