### ISSUE TITLE
Specify that docker destkop is required

### ISSUE THREAD

**Issue by lucas-salas** [firstlookmedia/dangerzone#130]
I was having issues with dangerzone getting hung up on my docker installation and couldn't access the app. 
<img width="408" alt="DangerZoneIssue" src="https://user-images.githubusercontent.com/10609483/134444734-fcc4dbc4-031a-4604-b5f4-86ae6dbed89a.png">
It seems to think I don't have docker installed, despite the following.
```zsh
> which docker
/opt/homebrew/bin/docker
```

I was going to try and build it from source but I noticed in the build instructions that you need to install docker desktop. **Installing docker desktop allowed me to access the app**, which  solved my problem. Unfortunately I ran into the same issue in this comment: https://github.com/firstlookmedia/dangerzone/issues/109#issuecomment-868702394 (probably m1 related).

Would be nice if we could specify that docker desktop is required for dangerzone to work.

**Comment by micahflee** [comment]
The latest version makes it clear that Docker Desktop is required.
