### ISSUE TITLE
Changed code signature in  MacOS v0.3?

### ISSUE THREAD

**Issue by suschizu** [firstlookmedia/dangerzone#133]
Hello - I've received a warning that the code-signature has changed from version 0.2.1 to 0.3

EXPECTED FIRST LOOK PRODUCTIONS, INC. (P24U45L8P5) but FOUND Micah Lee (N9B95FDWH4) 

can you confirm this? thanks

**Comment by micahflee** [comment]
Yes I can confirm that the code signature changed. It will change back probably by the next release.
