### ISSUE TITLE
Crash if docker service isn't running

### ISSUE THREAD

**Issue by micahflee** [firstlookmedia/dangerzone#38]
It should handle this smoothly, and offer to restart the docker service for you

**Comment by bungabunga** [comment]
is this the same issue?

https://gist.github.com/bungabunga/daf5c79ad52ea188c69884a9d85f53b4

on Ubuntu 19.10

**Comment by micahflee** [comment]
@bungabunga yes I think it is. You can run this, and then it should work:

```
sudo systemctl restart docker
sudo systemctl enable docker
```

**Comment by bungabunga** [comment]
thanks, but it seems those two commands don't help.

> sudo systemctl restart docker
gives me this:
https://gist.github.com/bungabunga/6d4c8a766aef898af85ae593e2974fc0

then
> systemctl status docker.service
gives me this:
https://gist.github.com/bungabunga/3f33e9517cd8916055d75c5d431f4405

**Comment by micahflee** [comment]
It looks like you're hitting this issue https://github.com/moby/moby/issues/34104

Basically, the docker service isn't starting because it's misconfigured (perhaps by default?). I'm actually hitting this same problem now in Fedora 31 with docker.

**Comment by micahflee** [comment]
@bungabunga your issue is a slightly different one than this one -- it's that your docker service itself isn't starting, not that dangerzone fails when the service isn't running. So I'm going to close this issue when I merge the PR that helps the user restart the docker service
