### ISSUE TITLE
Switch from podman to docker in fedora

### ISSUE THREAD

**Issue by micahflee** [firstlookmedia/dangerzone#51]
It looks like there are more differences between docker and podman that need to be handled. Specifically, while `document-to-pixels` works in docker, it fails with this error in podman.

```
root@e80fd5b9b501:/# sudo -u user /usr/local/bin/document-to-pixels-unpriv 
sudo: unable to resolve host e80fd5b9b501: Temporary failure in name resolution 
Traceback (most recent call last): 
  File "/usr/local/bin/document-to-pixels-unpriv", line 219, in <module> 
    main() 
  File "/usr/local/bin/document-to-pixels-unpriv", line 89, in main 
    mime_type = mime.from_file("/tmp/input_file") 
  File "/usr/lib/python3/dist-packages/magic/__init__.py", line 96, in from_file 
    with _real_open(filename): 
PermissionError: [Errno 13] Permission denied: '/tmp/input_file' 
root@e80fd5b9b501:/#  
```

**Comment by micahflee** [comment]
I think because I'm having docker/podman compatibility issues, and because #52 will likely cause even more issues, for the time-being I will switch Fedora from podman to docker. Then in the future, we can switch back to podman after thoroughly testing that everything works the same.

**Comment by anarcat** [comment]
would be great to have podman support, and i suspect it might even be a good idea to run your own container altogether, without any of those frameworks.

after all, all those features are basically stuff that lives inside the Linux kernel, you could call those apis yourself. :)
