### ISSUE TITLE
Better CLI support

### ISSUE THREAD

**Issue by micahflee** [firstlookmedia/dangerzone#53]
There should be a flag like `--no-gui` which requires a filename to be passed in, will skip opening a GUI, and will automatically do the conversion and save the file. This will allow dangerzone to be more easily used in scripts.

**Comment by serpest** [comment]
Can I work on this issue?

**Comment by micahflee** [comment]
@serpest sorry I'm just looking through old issues and seeing this. Are you still interested in working on it? You are definitely welcome to, and I can review your PR and discuss strategies for how it could work.

**Comment by pettitjr** [comment]
Would definitely love to see better CLI support. It'd be handy to be able to script this to run against a directory of files.

**Comment by anarcat** [comment]
i am wondering why the Docker container image doesn't just do that by default: take a file in, spew a file back out... that would make dangerzone usable without even the python stuff or the GUI, fairly straightforwardly...
