### ISSUE TITLE
Play nice with Docker CE installed from docker.com repositories

### ISSUE THREAD

**Issue by haplo** [firstlookmedia/dangerzone#60]
dangerzone fails to install (in Ubuntu 19.10 at least) when Docker is installed through the docker.com repositories.

Steps:
1. Install Docker CE following [these instructions](https://docs.docker.com/install/linux/docker-ce/ubuntu/).
2. Try to install Dangerzone following the wiki (Ubuntu instructions).

Expected: Dangerzone installs just fine.

Got: error because docker.io package cannot be installed (it conflicts with `docker-ce`):

```
$ sudo apt install dangerzone
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dangerzone : Depends: docker.io but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by micahflee** [comment]
I've confirmed your PR fixes the problem. Thanks!

**Comment by haplo** [comment]
Great! Thank you for Dangerzone @micahflee!
