### ISSUE TITLE
Docker Desktop requires Windows 10 Pro, does not work in Windows 10 Home

### ISSUE THREAD

**Issue by phazell** [firstlookmedia/dangerzone#62]
When trying to dl and install docker (via Docker for Windows Installer.exe), I keep getting the following error message: Installation failed: one prerequisite is not fulfilled.  Docker Desktop requires Windows 10 Pro or Enterprise version 15063 to run.

**Comment by micahflee** [comment]
Do you have Windows 10 Home? It's possible that Docker Desktop just isn't supported on Home.

**Comment by phazell** [comment]
But wouldn't that be a strange constraint for the said purpose of dangerzone, making it inutile for a great swath of it's possible users?

**Comment by TheodoreChu** [comment]
How can people with Windows 10 Home use Dangerzone?

**Comment by TheodoreChu** [comment]
How can people with Windows 10 Home use Dangerzone?

The latest version of Docker uses something called Hyper-V, which is available on Windows 10 Pro but not Windows 10 Home. 

Setting up an older version of Docker with [Docker toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/) would probably be too complicated for non-technical users.

Perhaps the easiest thing to do is to [upgrade to Windows 10 Pro](https://support.microsoft.com/en-us/help/12384/windows-10-upgrading-home-to-pro) or [purchase a license for $99](https://www.microsoft.com/en-us/p/windows-10-pro/df77x4d43rkt?activetab=pivot%3aoverviewtab) if your device allows it. 🤔

**Comment by phazell** [comment]
Thanks Theodore.  You're right.  Hyper-V is on every 64-bit versions of Windows 10 Pro, Enterprise, and Education.  Thanks, also, for the legacy Docker link.

**Comment by micahflee** [comment]
Sadly I think dangerzone just has to require Windows 10 Pro.

**Comment by TheodoreChu** [comment]
Here's an update on compatibility with Windows Home:

- Docker Desktop is available on Windows Home with WSL2:  https://docs.docker.com/docker-for-windows/install-windows-home/
- WSL2 requires the latest Windows version (2004 or build 19018), which can be found here: https://www.microsoft.com/en-us/software-download/windows10
- Information on how to set up WSL2 can be found here: https://docs.microsoft.com/en-us/windows/wsl/install-win10
- Dangerzone detects that Docker is installed, but does not properly detect when it is running: https://github.com/firstlookmedia/dangerzone/issues/89
