### ISSUE TITLE
dangerzone crashes if opening a file with Open With on MacOS

### ISSUE THREAD

**Issue by noonespecific** [firstlookmedia/dangerzone#66]
If going to Open With > dangerzone to open a file while dangerzone is not already running in the background, dangerzone launches and then promptly crashes. If dangerzone is already running in the background, the file loads in dangerzone as per the usual.

![image](https://user-images.githubusercontent.com/56607624/77674374-dee0b280-6f61-11ea-9318-c7ec3be687a2.png)

**Comment by andrewcrook** [comment]
@noonespecific is this related to #85 ?
do you see anything under the console app logs, anything similar to mine?

**Comment by micahflee** [comment]
This crash stopped happening.
