### ISSUE TITLE
No 'deb' Files for Ubuntu 18.04 and Derivatives

### ISSUE THREAD

**Issue by davidjmeier** [firstlookmedia/dangerzone#69]
I have spent some time in the development environment today to see how hard it would be to build deb variants for Ubuntu 18.04 and derivatives.  After filing a few pull requests for minor fixes and testing out if earlier versions of dependencies, that are native in 18.04 mainline, worked - I have come to the conclusion that dangerzone does indeed work as my minimal testing has yielded.

When building the deb using the out of the box installer I did the following...

1. Ran `build_deb.py`.
2. Extracted the contents of the compiled deb file in `deb_dist` folder: `dpkg-deb -R dangerzone_0.1.1-1_all.deb tmp`
3. Modified two files in the `tmp/DEBIAN` folder: `control` and `postinst`.
4. Modify single line in `control` to: `Depends: python3:any (>= 3.6~), ...`
5. Modify single line in `postinst` to:  `	py3compile -p dangerzone -V 3.6-`
6. Rebuild deb from the `deb_dist` folder root: `dpkg-deb -b tmp dangerzone_0.1.1-1_all-modified1804.deb`
7. Install the deb: `dpkg -i dpkg-deb -b tmp dangerzone_0.1.1-1_all-modified1804.deb`.

Again - I've only tested this minimally, but it does appear to work as expected.  It might be beneficial for many users to have `Bionic Beaver` available for use since this is likely the most widely deployed Ubuntu distribution at the current time.

**Comment by davidjmeier** [comment]
If anyone would like to test the deb let me know and I will post a build for test.

**Comment by micahflee** [comment]
I just fixed in #72 -- the next release will include an Ubuntu 18.04 package
