### ISSUE TITLE
Dangerzone for Win 8.1?

### ISSUE THREAD

**Issue by martin-nieuwoudt** [firstlookmedia/dangerzone#78]
Hi, 

It strikes me as rather odd advice to suggest that a user upgrade his operating system to Win 10 pro simply to get Dangerzone working. 

I have installed the Docker Toolbox. Can the Dangerzone developers not enable it to work with Win 8.1? Surely, this is not an insurmountable barrier, and you would dramatically increase your userbase.

**Comment by micahflee** [comment]
I was not aware that Dangerzone didn't work in Windows 8.1. Can you show me the error message you get when you try running it?

**Comment by martin-nieuwoudt** [comment]
Hi Micah,

I upgraded Win 8.1 to the newest release of Win 10 anyway. The difference
mostly has to do with support for the wsl 2 virtual machine system, which
8.1 does not have.  I have installed Docker and Ubuntu and Dangerzone works
fine on Win 10 Pro with a single SSD.

I now have another interesting problem: I also installed the above onto a
machine that has an OS installed on an SSD, but has an additional HDD for
'Data'. I have tried installing all of the above and everything works until
Dangerzone wants to output the final 'safe' pdf file. The error says,
'Drive not shared' and points me to a  location inside Docker. I am not
sure why this is happening. Have you got a suggestion?

regards,
Martin

**Comment by micahflee** [comment]
> The error says, 'Drive not shared' and points me to a  location inside Docker. I am not sure why this is happening. Have you got a suggestion?

All the magic in dangerzone happens in Docker. The problem here is that Docker doesn't have permission to access your separate drive. You need to give Docker this permission by making it a "shared drive". Search this for "shared drive" for more information https://docs.docker.com/docker-for-windows/#docker-settings-dialog
