### ISSUE TITLE
Dependency problems

### ISSUE THREAD

**Issue by w1j** [firstlookmedia/dangerzone#88]
Installing on PureOS linux on a desktop from the command line I get:

dpkg: error processing package docker.io (--configure):
 installed docker.io package post-installation script subprocess returned error exit status 1
Setting up libintl-xs-perl (1.26-2+b4) ...
Setting up git (1:2.20.1-2+deb10u3) ...
dpkg: dependency problems prevent configuration of dangerzone:
 dangerzone depends on docker.io | docker-ce; however:
  Package docker.io is not configured yet.
  Package docker-ce is not installed.

dpkg: error processing package dangerzone (--configure):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for systemd (241-7pureos0.2) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Errors were encountered while processing:
 docker.io
 dangerzone
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by micahflee** [comment]
Try installing Docker-CE first before installing dangerzone. There's a link to Docker-CE instructions in the Dangerzone linux installation instructions: https://github.com/firstlookmedia/dangerzone/wiki/Installing-Dangerzone#install-in-linux
