### ISSUE TITLE
MacOS package fails to start on Big Sur

### ISSUE THREAD

**Issue by simonft** [firstlookmedia/dangerzone#97]
I installed the MacOS package on Big Sur. When running, the app shows an icon in the doc but never actually opens. Instead it just hangs at 90-100% cpu until it is killed. Below is the (probably not very helpful) output of running it on the command line.

```
infratest@Infras-MacBook-Air ~ % /Applications/Dangerzone.app/Contents/MacOS/dangerzone
Temporary directories created, dangerous=/tmp/dangerzone-pixel-boe446u2, safe=/tmp/dangerzone-safe-a8zg680p
Executing: /Applications/Dangerzone.app/Contents/MacOS/dangerzone-container ls
Temporary directories created, dangerous=/tmp/dangerzone-pixel-az0d881h, safe=/tmp/dangerzone-safe-n1b19jx8
```

**Comment by ahmetasabanci** [comment]
I'm having the same issue. Not sure why it's happening but it always stops responding when I start it and the only thing I can do is to force quit.
